name: build

on: [push, pull_request]

jobs:
  build-dart-latest:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run dependency validator
      run: pub run dependency_validator
    - name: Run dartanalyzer
      run: dartanalyzer --fatal-warnings --fatal-infos --fatal-lints bin/ lib/ test/
    - name: Run dartfmt
      run: dartfmt --set-exit-if-changed -n .
    - name: Run tests
      run: pub run test --coverage=coverage

  build-dart-2-4:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:2.4

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run dependency validator
      run: pub run dependency_validator
    - name: Run dartanalyzer
      run: dartanalyzer --fatal-warnings --fatal-infos --fatal-lints bin/ lib/ test/
    - name: Run dartfmt
      run: dartfmt --set-exit-if-changed -n .
    - name: Run tests
      run: pub run test
